Repository AY2021S2-CS2103T-W14-1/tp, pull requests merged in 2021-04, with the labels that each got.

#123 Fix broken UI for dates and meetings with long descriptions
  src/main/java/seedu/address/ui/PersonDetailsCard.java
  src/main/resources/view/PersonDetailsCard.fxml
Labels: type.Bug

#133 Fix bug with group when editing person name.
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/GroupHashMap.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/testutil/GroupBuilder.java
Labels: priority.High, type.Bug

#135 Fix Add with missing birthday field
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: type.Bug

#139 Add command word to autocomplete strings
  src/main/java/seedu/address/logic/commands/Commands.java
Labels: type.Bug, type.Chore

#137 Add updateUpcomingDates() to addPerson()
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug, type.Chore

#136 Fix Debt toString
  src/main/java/seedu/address/model/person/Debt.java
Labels: type.Bug

#141 Remove Picture Description in Person toString
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Bug

#206 Update upcoming events and person details on `clear`
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: priority.Medium, severity.Medium, type.Bug

#144 Fix bug where PersonDetailsTab still shows person after deletion
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Bug

#207 Fixes for bugs concerning goals and meetings
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonDetailsCard.java
Labels: type.Bug, type.Chore

#208 Profile picture issues
  docs/UserGuide.md
  src/main/java/seedu/address/ui/ProfilePicture.java
Labels: priority.Medium, severity.Medium, type.Bug, type.Docs

#211 Find regex ug update
  docs/UserGuide.md
Labels: type.Docs

#209 Fix special date issues
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteDateCommand.java
  src/test/java/seedu/address/logic/commands/DeleteDateCommandTest.java
Labels: severity.Low, type.Bug, type.Docs

#217 Add tests for Goal
  src/test/java/seedu/address/model/person/GoalTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Chore

#218 Add deadline test for PersonTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddDateCommandTest.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPictureCommandTest.java
  src/test/java/seedu/address/logic/commands/ChangeDebtCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteDateCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePictureCommandTest.java
  src/test/java/seedu/address/logic/commands/DetailsCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TestDataUtil.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Chore

#219 Add tests for `SetGoalCommand` and `SetGoalCommandParser`
  src/main/java/seedu/address/logic/commands/SetGoalCommand.java
  src/main/java/seedu/address/logic/parser/SetGoalCommandParser.java
  src/main/java/seedu/address/model/person/Goal.java
  src/test/java/seedu/address/logic/commands/SetGoalCommandTest.java
  src/test/java/seedu/address/logic/parser/SetGoalCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Chore

#220 Validate file signature of images
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/AddPictureCommand.java
  src/main/java/seedu/address/model/person/Picture.java
  src/main/java/seedu/address/ui/PersonDetailsCard.java
  src/test/data/FileTest/jpg_file.jpg
  src/test/data/FileTest/json_file.json
  src/test/data/FileTest/pdf_file.pdf
  src/test/data/FileTest/png_file.png
  src/test/data/FileTest/text_file.txt
  src/test/java/seedu/address/commons/util/FileUtilTest.java
Labels: type.Chore

#222 Fix formatting issue for `add-group`'s success message
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/model/group/Group.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
Labels: type.Bug, type.Chore

#214 Fix Clickable List Cell
  src/main/java/seedu/address/ui/GroupListPanel.java
  src/main/java/seedu/address/ui/PersonDetailsTab.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/StreaksTab.java
  src/main/java/seedu/address/ui/UpcomingEventsTab.java
Labels: type.Bug

#221 UI/UX improvements
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/AddDateCommand.java
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/AddPictureCommand.java
  src/main/java/seedu/address/logic/commands/ChangeDebtCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDateCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/commands/DeletePictureCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SetGoalCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/GroupListPanel.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#229 Sort dates and meetings when adding and parsing
  src/main/java/seedu/address/logic/commands/AddDateCommand.java
  src/main/java/seedu/address/logic/commands/ChangeDebtCommand.java
  src/main/java/seedu/address/model/person/Debt.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: type.Chore

#228 Add tests for `ThemeCommandParser`
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ThemeCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ThemeManager.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/parser/ThemeCommandParserTest.java
Labels: type.Chore

#233 Update DG for tabs switching
  docs/DeveloperGuide.md
  docs/diagrams/SwitchTabSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/SwitchTabSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Docs

#223 Fix group
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/GroupHashMap.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/GroupListPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/group/GroupHashMapTest.java
Labels: type.Bug

#236 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Autocomplete.png
  docs/images/PersonDetails.png
  docs/images/StreaksDashboard.png
  docs/images/Ui.png
  docs/images/UiAnnotated.png
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/commons/core/DetailsPanelTab.java
  src/main/java/seedu/address/ui/DetailsPanel.java
Labels: type.Docs

#235 Update test manual for `find`, `set-goal`, and `theme` command
  docs/DeveloperGuide.md
Labels: type.Chore, type.Docs

#234 Debt fix
  src/main/java/seedu/address/logic/commands/ChangeDebtCommand.java
  src/main/java/seedu/address/logic/parser/ChangeDebtParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Debt.java
  src/test/java/seedu/address/logic/commands/ChangeDebtCommandTest.java
  src/test/java/seedu/address/model/person/DebtTest.java
Labels: type.Bug

#239 Add List Test
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: type.Chore

#248 Update favicon and add codecov badge
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/favicon.ico
  docs/images/Autocomplete.png
  docs/images/FriendDex.png
  docs/images/PersonDetails.png
  docs/images/StreaksDashboard.png
  docs/images/Ui.png
  docs/images/UiAnnotated.png
  docs/images/findAlexDavidResult.png
  docs/index.md
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/frienddex_32.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Docs, type.Enhancement

#237 Update UG
  docs/UserGuide.md
Labels: type.Docs

#246 Add Assyarul's PPP
  docs/AboutUs.md
  docs/team/assyarul.md
  docs/team/johndoe.md
Labels: type.Docs

#258 Fix command feedback for add-group and bug for delete group
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
Labels: type.Bug

#259 Fix Debt Display on Details Panel and -ve Debt
  src/main/java/seedu/address/model/person/Debt.java
  src/main/java/seedu/address/ui/PersonDetailsCard.java
Labels: type.Bug

#243 Update DG to include predefined themes
  docs/DeveloperGuide.md
  docs/diagrams/ThemeCommandSequenceDiagram.puml
  docs/diagrams/ThemeFactoryLoadSequenceDiagram.puml
  docs/diagrams/ThemeInitializationSequenceDiagram.puml
  docs/images/ThemeCommandSequenceDiagram.png
  docs/images/ThemeFactoryLoadSequenceDiagram.png
  docs/images/ThemeInitializationSequenceDiagram.png
Labels: type.Docs

#261 Add chesterhow's PPP
  docs/AboutUs.md
  docs/index.md
  docs/team/chesterhow.md
  docs/team/ivantjh.md
Labels: type.Docs

#262 Write manual testing portion for `edit` command
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Docs

#263 Add PPP for Lin Lue
  docs/team/lue.md
Labels: type.Docs

#266 Add portfolio for Lin Lue
  docs/AboutUs.md
Labels: type.Chore, type.Docs

#269 Final cleanup for UG DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Docs

#273 Add intro to DG
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
Labels: type.Docs

#277 Add credit for regex
  src/main/java/seedu/address/model/person/Email.java
Labels: type.Chore, type.Docs
