Repository AY2021S2-CS2103T-W14-1/tp, pull requests merged in 2021-03, with the labels that each got.

#41 Add meeting cmd
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/commons/util/TimeUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMeetingParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Meeting.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedMeeting.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/parser/InputParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story

#43 Pattern search for find
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsPatternPredicate.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsPatternPredicateTest.java
Labels: type.Story

#42 Create Birthday Field
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/DateCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#45 Add friend group
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddGroupParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/GroupHashMap.java
  src/main/java/seedu/address/model/group/exceptions/DuplicateGroupException.java
  src/main/java/seedu/address/model/group/exceptions/GroupNotFoundException.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/AddGroupCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/group/GroupHashMapTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/GroupBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#3 Add capabilites to change application theme
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/commands/ThemeCommand.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/main/java/seedu/address/logic/parser/ThemeCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/Theme.java
  src/main/java/seedu/address/ui/ThemeFactory.java
  src/main/java/seedu/address/ui/ThemeManager.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/UiPart.java
  src/main/java/seedu/address/ui/exceptions/InvalidThemeException.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/Template.css
  src/test/data/ThemeTest/default.template.css
  src/test/data/ThemeTest/invalid.content.txt
  src/test/data/ThemeTest/invalid.theme.json
  src/test/data/ThemeTest/malformed.theme.json
  src/test/data/ThemeTest/valid.theme.json
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/ui/ThemeFactoryTest.java
  src/test/java/seedu/address/ui/ThemeManagerTest.java
  src/test/java/seedu/address/ui/ThemeTest.java
  theme/mocha.dark.json
  theme/solarized.dark.json
  theme/tomorrow.dark.json
Labels: type.Story

#48 Delete meeting
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Story

#51 Add Friend Group List Ui
  src/main/java/seedu/address/ui/GroupListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/GroupListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#54 Bug Fix Group List Ui
  src/main/java/seedu/address/ui/GroupListPanel.java
Labels: type.Bug

#53 Add Profile Picture
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/AddDateCommand.java
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/AddPictureCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDateCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPictureCommandParser.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Picture.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPicture.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UserPrefsStorage.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story

#58 Enhance List Command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/group/GroupHashMap.java
  src/main/java/seedu/address/ui/GroupListPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/InputParserTest.java
Labels: type.Enhancement

#74 Update UG and UI diagram in DG
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Chore

#75 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Chore

#76 Document implementation details for Details Panel tab switching
  docs/DeveloperGuide.md
Labels: type.Chore

#79 Add documentation for theme and set-goal commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ThemeCommandSequenceDiagram.puml
  docs/diagrams/ThemeInitializationSequenceDiagram.puml
  docs/images/ThemeCommandSequenceDiagram.png
  docs/images/ThemeInitializationSequenceDiagram.png
Labels: type.Chore

#78 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddGroupSequenceDiagram.puml
  docs/diagrams/CommandSequenceDiagram.puml
  docs/images/AddGroupSequenceDiagram.png
  docs/images/CommandSequenceDiagram.png
Labels: type.Chore

#72 Add autocomplete for commands
  build.gradle
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/Commands.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ThemeFactory.java
  src/main/resources/view/Template.css
  src/test/data/ThemeTest/default.template.css
Labels: type.Story

#77 Fix Grouplist
  src/main/java/seedu/address/ui/GroupListPanel.java
Labels: type.Bug

#82 Make adding tabs to DetailsPanel easier
  src/main/java/seedu/address/ui/DetailsPanel.java
  src/main/java/seedu/address/ui/PersonDetailsTab.java
  src/main/java/seedu/address/ui/UpcomingEventsTab.java
  src/main/resources/view/DetailsPanel.fxml
  src/main/resources/view/PersonDetailsTab.fxml
  src/main/resources/view/UpcomingEventsTab.fxml
Labels: type.Enhancement

#83 Allow users to set meeting goals for person
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SetGoalCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetGoalCommandParser.java
  src/main/java/seedu/address/model/person/Goal.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story

#96 Branch theme fix
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ThemeCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ThemeManager.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/data/ThemeTest/default.template.css
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: type.Bug

#92 Rename default data file and app title to frienddex
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Chore

#93 Update screenshots in UG
  .gitignore
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
  theme/sweetlove.json
Labels: type.Chore

#97 Update UG
  docs/UserGuide.md
  docs/images/UiAnnotated.png
Labels: type.Chore

#103 Ship application with sample themes
  .gitignore
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ThemeCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ThemeFactory.java
  src/main/java/seedu/address/ui/ThemeManager.java
  src/main/resources/themes/dkeg-panel
  src/main/resources/themes/monokai
  src/main/resources/themes/mostly-bright
  src/main/resources/themes/paraiso-light
  src/main/resources/themes/pulp
  src/main/resources/themes/s3r0-modified
  src/main/resources/themes/sweetlove
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/Template.css
  src/test/data/ThemeTest/default.template.css
  src/test/java/seedu/address/ui/ThemeFactoryTest.java
  src/test/java/seedu/address/ui/ThemeManagerTest.java
  theme/mocha.dark.json
Labels: priority.Medium

#107 Remove s
  src/main/resources/view/Template.css
Labels: type.Bug

#84 Add Debt Feature
  src/main/java/seedu/address/logic/commands/ChangeDebtCommand.java
  src/main/java/seedu/address/logic/commands/Commands.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ChangeDebtParser.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Debt.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonDetailsCard.java
  src/main/resources/view/PersonDetailsCard.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/ChangeDebtCommandTest.java
  src/test/java/seedu/address/model/person/DebtTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story

#105 Add tests for `add-date`, `del-date` and `details` commands
  src/main/java/seedu/address/model/person/Event.java
  src/test/java/seedu/address/logic/commands/AddDateCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteDateCommandTest.java
  src/test/java/seedu/address/logic/commands/DetailsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddDateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteDateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DetailsCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: type.Chore

#109 Create UI components for dates and meetings
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/PersonDetailsCard.java
  src/main/resources/view/EventCard.fxml
  src/main/resources/view/PersonDetailsCard.fxml
  src/main/resources/view/PersonDetailsTab.fxml
  src/main/resources/view/UpcomingEventsTab.fxml
Labels: type.Enhancement

#113 Implement `view` command
  src/main/java/seedu/address/commons/core/DetailsPanelTab.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/Commands.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/ui/DetailsPanel.java
  src/test/java/seedu/address/logic/commands/DetailsCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: type.Enhancement, type.Story

#112 Ug theme update
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ThemeCommand.java
Labels: type.Chore

#104 Add Delete Group Command
  src/main/java/seedu/address/logic/commands/Commands.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/InputParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/GroupListPanel.java
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/AddGroupCommandParserTest.java
Labels: type.Enhancement

#119 Minor changes to `set-goal`
  src/main/java/seedu/address/logic/commands/SetGoalCommand.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Bug
